# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    directories:
      - "/"
      - "/http-cache"
      - "/http-cache-darkbird"
      - "/http-cache-mokadeser"
      - "/http-cache-quickcache"
      - "/http-cache-reqwest"
      - "/http-cache-surf"
    schedule:
      interval: "weekly"
    ignore:
        # These are peer deps of Cargo and should not be automatically bumped
        - dependency-name: "semver"
        - dependency-name: "crates-io"
