[package]
name = "http-cache-tests"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.66"
async-std = { version = "1.12.0", features = ["attributes"] }
cacache = "10.0.1"
http = "0.2.8"
http-cache-semantics = "1.0.1"
http-types = "2.12.0"
reqwest = "0.11.13"
reqwest-middleware = "0.2.0"
surf = "2.3.2"
tokio = { version = "1.21.2", features = ["macros", "rt-multi-thread"] }
url = "2.3.1"
wiremock = "0.5.15"

[dependencies.http-cache]
path = "../http-cache"
version = "0.7.2"
features = ["with-http-types", "manager-moka"]

[dependencies.http-cache-reqwest]
path = "../http-cache-reqwest"
version = "0.5.2"

[dependencies.http-cache-surf]
path = "../http-cache-surf"
version = "0.5.2"
