name: msrv

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Verify MSRV
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - http-cache
          - http-cache-reqwest
          - http-cache-surf
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-binstall
      - run: cargo binstall --version 0.18.4 --no-confirm cargo-msrv
      - name: cargo msrv verify ${{ matrix.path }}
        run: cargo msrv verify --path ${{ matrix.path }}
