name: msrv

on:
  push:
    branches: [main]
  pull_request:

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Verify MSRV
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-binstall
      - run: cargo binstall --version 0.15.1 --no-confirm cargo-msrv
      - name: Run cargo msrv http-cache
        working-directory: ./http-cache
        run: cargo msrv verify
      - name: Run cargo msrv http-cache-quickcache
        working-directory: ./http-cache-quickcache
        run: cargo msrv verify
      - name: Run cargo msrv http-cache-darkbird
        working-directory: ./http-cache-darkbird
        run: cargo msrv verify
